### ISSUE TITLE
plugin giving error in laravel 7.x

### ISSUE THREAD

**Issue by subhankhalid402** [fico7489/LaravelPivot#69]
I am using this plugin in laravel 7.x

```
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
class Lead extends Model
{
    use PivotEventTrait;

```

when i add **use PivotEventTrait**. it starts giving error. 
```
Undefined offset: 0

Illuminate\\Foundation\\Bootstrap\\HandleExceptions::handleError(8, 'Undefined offset: 0', 'D:\\wamp64\\www\\sa-api\\vendor\\laravel\\telescope\\src\\Watchers\\ModelWatcher.php', 36, array(2))
```

**Comment by BKorenek** [comment]
Experiencing the same issue. 

```
[2020-07-18 23:13:53] local.ERROR: Undefined offset: 0 {"userId":10000,"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /var/www/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:36)
[stacktrace]
#0 /var/www/vendor/laravel/telescope/src/Watchers/ModelWatcher.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/vendor...', 36, Array)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(378): Laravel\\Telescope\\Watchers\\ModelWatcher->recordAction('eloquent.create...', Array)
#2 /var/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.create...', Array)
#3 /var/www/vendor/fico7489/laravel-pivot/src/Traits/ExtendFireModelEventTrait.php(37): Illuminate\\Events\\Dispatcher->dispatch('eloquent.create...', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(886): App\\User->fireModelEvent('created', false)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(728): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#6 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(454): Illuminate\\Database\\Eloquent\\Model->save()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(433): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\User))
#8 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(455): tap(Object(App\\User), Object(Closure))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->updateOrCreate(Array, Array)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1732): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'updateOrCreate', Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1744): Illuminate\\Database\\Eloquent\\Model->__call('updateOrCreate', Array)
#12 /var/www/app/Http/Controllers/Auth/LoginController.php(83): Illuminate\\Database\\Eloquent\\Model::__callStatic('updateOrCreate', Array)
#13 [internal function]: App\\Http\\Controllers\\Auth\\LoginController->handleProviderCallback()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handleProviderC...', Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\LoginController), 'handleProviderC...')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\EncryptedStore), Object(Closure))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/app/Http/Middleware/BrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\BrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#59 /var/www/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#60 {main}
"}
```

I believe it may have something to do with telescope since that's where my trace ended up. @subhankhalid402 can you confirm that you are / are not using telescope?

It appears that the method `recordAction` on `ModelWatcher.php` takes a `$data` array variable, I believe when this variable is passed in from an event from this plugin, the index is `model` instead of 0 based. 

```
[2020-07-18 23:18:05] local.INFO: Array
(
    [model] => App\User Object
        (
            [casts] => Array
                (
                    [github_user] => array
                )

            [fillable:protected] => Array
                (
                    [0] => name
                    [1] => email
                    [2] => password
                    [3] => github_name
                    [4] => github_email
                    [5] => github_nickname
                    [6] => github_id
                    [7] => github_refresh_token
                    [8] => github_token
                    [9] => github_avatar
                    [10] => github_expires_in
                    [11] => github_user
                )
```

Compared to the normal array
```
[2020-07-18 23:18:05] local.INFO: Array
(
    [0] => App\UserSettings Object
        (
            [fillable:protected] => Array
                (
                    [0] => dark_mode
                    [1] => user_id
                )

            [connection:protected] => mysql
            [table:protected] => user_settings
            [primaryKey:protected] => id
            [keyType:protected] => int
            [incrementing] => 1
            [with:protected] => Array
                (
                )

            [withCount:protected] => Array
                (
                )
```

**Comment by judefdoo** [comment]
Experiencing the same. As @BKorenek mentioned, this issue comes only when telescope is enabled. 

But I believe it's to do with the structure of payload dispatched with the event. 

Managed to resolve this by extending the _fireModelEvent_ in \Fico7489\Laravel\Pivot\Traits\ExtendFireModelEventTrait to match the fireModelEvent of \Illuminate\Database\Eloquent\Concerns\HasEvents trait.

```
<?php

namespace App\Traits\Pivot;

use Fico7489\Laravel\Pivot\Traits\ExtendFireModelEventTrait;

trait ExtendFireModelEventCustom
{

    use ExtendFireModelEventTrait{
        ExtendFireModelEventTrait::fireModelEvent as parentFireModelEvent;
    }

    /**
     * Relation Name of a Model.
     *
     * @var string
     */
    protected $customPivotRelationName;

    /**
     * Pivot Ids of Many to Many relationship of the model.
     *
     * @var string
     */
    protected $customPivotIds;

    /**
     * Pivot Ids Attributes of Many to Many relationship of the model.
     *
     * @var string
     */
    protected $customPivotIdsAttributes; 

    /**
     * Fire the given event for the model.
     *
     * @param string $event
     * @param bool   $halt
     *
     * @return mixed
     */
    public function fireModelEvent($event, $halt = true, $relationName = null, $ids = [], $idsAttributes = [])
    {
        if (!isset(static::$dispatcher)) {
            return true;
        }

        // First, we will get the proper method to call on the event dispatcher, and then we
        // will attempt to fire a custom, object based event for the given event. If that
        // returns a result we can return that result, or we'll call the string events.
        $method = $halt ? 'until' : 'dispatch';

        $result = $this->filterModelEventResults(
            $this->fireCustomModelEvent($event, $method)
        );
        
        if (false === $result) {
            return false;
        }

        $this->customPivotRelationName = $relationName;
        $this->customPivotIds = $ids;
        $this->customPivotIdsAttributes = $idsAttributes;
        // $payload = ['model' => $this, 'relation' => $relationName, 'pivotIds' => $ids, 'pivotIdsAttributes' => $idsAttributes];

        return !empty($result) ? $result : static::$dispatcher->{$method}(
            "eloquent.{$event}: ".static::class, $this
        );
    }
}

```

Not sure if this is the best way to do it though. And I had to change the listener to the same way how we catch standard eloquent events rather than what's suggested in the documentation.

ex:
```
    static::pivotAttaching(function ($model) {
        //
        dump($model->customPivotRelationName); //ex
    });
```

instead of 

```
    static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //
    });
```

**Comment by WL1981** [comment]
Experiencing the same issue.

**Comment by fico7489** [comment]
closing, it is outdated
